bumped to R 4.0.2, rocker created a new method for making their containers which build MUCH faster, but are a little larger

diff --git a/old_Dockerfile b/old_Dockerfile
--- a/old_Dockerfile
+++ b/old_Dockerfile
@@ -1,6 +1,233 @@
+####base r block 
+FROM debian:stretch
 
-FROM rocker/rstudio:3.6.1
 
+ARG R_VERSION
+ARG BUILD_DATE
+ENV BUILD_DATE ${BUILD_DATE:-2020-09-20}
+ENV R_VERSION=${R_VERSION:-4.0.1} \
+    LC_ALL=en_US.UTF-8 \
+    LANG=en_US.UTF-8 \
+    TERM=xterm
+
+
+RUN apt-get update \
+  && apt-get install -y --no-install-recommends \
+    bash-completion \
+    ca-certificates \
+    file \
+    fonts-texgyre \
+    g++ \
+    gfortran \
+    gsfonts \
+    libblas-dev \
+    libbz2-1.0 \
+    libcurl3 \
+    libicu57 \
+    libjpeg62-turbo \
+    libopenblas-dev \
+    libpangocairo-1.0-0 \
+    libpcre3 \
+    libpng16-16 \
+    libreadline7 \
+    libtiff5 \
+    liblzma5 \
+    libpcre2-dev \
+    locales \
+    make \
+    unzip \
+    zip \
+    zlib1g \
+  && echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen \
+  && locale-gen en_US.utf8 \
+  && /usr/sbin/update-locale LANG=en_US.UTF-8 \
+  && BUILDDEPS="curl \
+    default-jdk \
+    libbz2-dev \
+    libcairo2-dev \
+    libcurl4-openssl-dev \
+    libpango1.0-dev \
+    libjpeg-dev \
+    libicu-dev \
+    libpcre3-dev \
+    libpng-dev \
+    libreadline-dev \
+    libtiff5-dev \
+    liblzma-dev \
+    libx11-dev \
+    libxt-dev \
+    perl \
+    tcl8.6-dev \
+    tk8.6-dev \
+    texinfo \
+    texlive-extra-utils \
+    texlive-fonts-recommended \
+    texlive-fonts-extra \
+    texlive-latex-recommended \
+    x11proto-core-dev \
+    xauth \
+    xfonts-base \
+    xvfb \
+    zlib1g-dev" \
+  && apt-get install -y --no-install-recommends $BUILDDEPS \
+  && cd tmp/ \
+  ## Download source code
+  && curl -O https://cran.r-project.org/src/base/R-4/R-${R_VERSION}.tar.gz \
+  ## Extract source code
+  && tar -xf R-${R_VERSION}.tar.gz \
+  && cd R-${R_VERSION} \
+  ## Set compiler flags
+  && R_PAPERSIZE=letter \
+    R_BATCHSAVE="--no-save --no-restore" \
+    R_BROWSER=xdg-open \
+    PAGER=/usr/bin/pager \
+    PERL=/usr/bin/perl \
+    R_UNZIPCMD=/usr/bin/unzip \
+    R_ZIPCMD=/usr/bin/zip \
+    R_PRINTCMD=/usr/bin/lpr \
+    LIBnn=lib \
+    AWK=/usr/bin/awk \
+    CFLAGS="-g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g" \
+    CXXFLAGS="-g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g" \
+  ## Configure options
+  ./configure --enable-R-shlib \
+               --enable-memory-profiling \
+               --with-readline \
+               --with-blas \
+               --with-tcltk \
+               --disable-nls \
+               --with-recommended-packages \
+  ## Build and install
+  && make \
+  && make install \
+  ## Add a default CRAN mirror
+  && echo "options(repos = c(CRAN = 'https://cran.rstudio.com/'), download.file.method = 'libcurl')" >> /usr/local/lib/R/etc/Rprofile.site \
+  ## Add a library directory (for user-installed packages)
+  && mkdir -p /usr/local/lib/R/site-library \
+  && chown root:staff /usr/local/lib/R/site-library \
+  && chmod g+ws /usr/local/lib/R/site-library \
+  ## Fix library path
+  && sed -i '/^R_LIBS_USER=.*$/d' /usr/local/lib/R/etc/Renviron \
+  && echo "R_LIBS_USER=\${R_LIBS_USER-'/usr/local/lib/R/site-library'}" >> /usr/local/lib/R/etc/Renviron \
+  && echo "R_LIBS=\${R_LIBS-'/usr/local/lib/R/site-library:/usr/local/lib/R/library:/usr/lib/R/library'}" >> /usr/local/lib/R/etc/Renviron \
+  ## install packages from date-locked MRAN snapshot of CRAN
+  && [ -z "$BUILD_DATE" ] && BUILD_DATE=$(TZ="America/Los_Angeles" date -I) || true \
+  && MRAN=https://mran.microsoft.com/snapshot/${BUILD_DATE} \
+  && echo MRAN=$MRAN >> /etc/environment \
+  && export MRAN=$MRAN \
+  && echo "options(repos = c(CRAN='$MRAN'), download.file.method = 'libcurl')" >> /usr/local/lib/R/etc/Rprofile.site \
+  ## Use littler installation scripts
+  && Rscript -e "install.packages(c('littler', 'docopt'), repo = '$MRAN')" \
+  && ln -s /usr/local/lib/R/site-library/littler/examples/install2.r /usr/local/bin/install2.r \
+  && ln -s /usr/local/lib/R/site-library/littler/examples/installGithub.r /usr/local/bin/installGithub.r \
+  && ln -s /usr/local/lib/R/site-library/littler/bin/r /usr/local/bin/r \
+  ## Clean up from R source install
+  && cd / \
+  && rm -rf /tmp/* \
+  && apt-get remove --purge -y $BUILDDEPS \
+  && apt-get autoremove -y \
+  && apt-get autoclean -y \
+  && rm -rf /var/lib/apt/lists/*
+##### Rstudio block
+ARG RSTUDIO_VERSION
+ENV RSTUDIO_VERSION=${RSTUDIO_VERSION:-1.2.5019}
+ARG S6_VERSION
+ARG PANDOC_TEMPLATES_VERSION
+ENV S6_VERSION=${S6_VERSION:-v1.21.7.0}
+ENV S6_BEHAVIOUR_IF_STAGE2_FAILS=2
+ENV PATH=/usr/lib/rstudio-server/bin:$PATH
+ENV PANDOC_TEMPLATES_VERSION=${PANDOC_TEMPLATES_VERSION:-2.9}
+
+## Download and install RStudio server & dependencies
+## Attempts to get detect latest version, otherwise falls back to version given in $VER
+## Symlink pandoc, pandoc-citeproc so they are available system-wide
+RUN apt-get update \
+  && apt-get install -y --no-install-recommends \
+    file \
+    git \
+    libapparmor1 \
+    libcurl4-openssl-dev \
+    libedit2 \
+    libssl-dev \
+    lsb-release \
+    psmisc \
+    procps \
+    python-setuptools \
+    sudo \
+    wget \
+    libclang-dev \
+    libclang-3.8-dev \
+    libobjc-6-dev \
+    libclang1-3.8 \
+    libclang-common-3.8-dev \
+    libllvm3.8 \
+    libobjc4 \
+    libgc1c2 \
+  && if [ -z "$RSTUDIO_VERSION" ]; then RSTUDIO_URL="https://www.rstudio.org/download/latest/stable/server/debian9_64/rstudio-server-latest-amd64.deb"; else RSTUDIO_URL="http://download2.rstudio.org/server/debian9/x86_64/rstudio-server-${RSTUDIO_VERSION}-amd64.deb"; fi \
+  && wget -q $RSTUDIO_URL \
+  && dpkg -i rstudio-server-*-amd64.deb \
+  && rm rstudio-server-*-amd64.deb \
+  ## Symlink pandoc & standard pandoc templates for use system-wide
+  && ln -s /usr/lib/rstudio-server/bin/pandoc/pandoc /usr/local/bin \
+  && ln -s /usr/lib/rstudio-server/bin/pandoc/pandoc-citeproc /usr/local/bin \
+  && git clone --recursive --branch ${PANDOC_TEMPLATES_VERSION} https://github.com/jgm/pandoc-templates \
+  && mkdir -p /opt/pandoc/templates \
+  && cp -r pandoc-templates*/* /opt/pandoc/templates && rm -rf pandoc-templates* \
+  && mkdir /root/.pandoc && ln -s /opt/pandoc/templates /root/.pandoc/templates \
+  && apt-get clean \
+  && rm -rf /var/lib/apt/lists/ \
+  ## RStudio wants an /etc/R, will populate from $R_HOME/etc
+  && mkdir -p /etc/R \
+  ## Write config files in $R_HOME/etc
+  && echo '\n\
+    \n# Configure httr to perform out-of-band authentication if HTTR_LOCALHOST \
+    \n# is not set since a redirect to localhost may not work depending upon \
+    \n# where this Docker container is running. \
+    \nif(is.na(Sys.getenv("HTTR_LOCALHOST", unset=NA))) { \
+    \n  options(httr_oob_default = TRUE) \
+    \n}' >> /usr/local/lib/R/etc/Rprofile.site \
+  && echo "PATH=${PATH}" >> /usr/local/lib/R/etc/Renviron \
+  ## Need to configure non-root user for RStudio
+  && useradd rstudio \
+  && echo "rstudio:rstudio" | chpasswd \
+	&& mkdir /home/rstudio \
+	&& chown rstudio:rstudio /home/rstudio \
+	&& addgroup rstudio staff \
+  ## Prevent rstudio from deciding to use /usr/bin/R if a user apt-get installs a package
+  &&  echo 'rsession-which-r=/usr/local/bin/R' >> /etc/rstudio/rserver.conf \
+  ## use more robust file locking to avoid errors when using shared volumes:
+  && echo 'lock-type=advisory' >> /etc/rstudio/file-locks \
+  ## configure git not to request password each time
+  && git config --system credential.helper 'cache --timeout=3600' \
+  && git config --system push.default simple \
+  ## Set up S6 init system
+  && wget -P /tmp/ https://github.com/just-containers/s6-overlay/releases/download/${S6_VERSION}/s6-overlay-amd64.tar.gz \
+  && tar xzf /tmp/s6-overlay-amd64.tar.gz -C / \
+  && mkdir -p /etc/services.d/rstudio \
+  && echo '#!/usr/bin/with-contenv bash \
+          \n## load /etc/environment vars first: \
+  		  \n for line in $( cat /etc/environment ) ; do export $line ; done \
+          \n exec /usr/lib/rstudio-server/bin/rserver --server-daemonize 0' \
+          > /etc/services.d/rstudio/run \
+  && echo '#!/bin/bash \
+          \n rstudio-server stop' \
+          > /etc/services.d/rstudio/finish \
+  && mkdir -p /home/rstudio/.rstudio/monitored/user-settings \
+  && echo 'alwaysSaveHistory="0" \
+          \nloadRData="0" \
+          \nsaveAction="0"' \
+          > /home/rstudio/.rstudio/monitored/user-settings/user-settings \
+  && chown -R rstudio:rstudio /home/rstudio/.rstudio
+
+COPY userconf.sh /etc/cont-init.d/userconf
+
+## running with "-e ADD=shiny" adds shiny server
+COPY add_shiny.sh /etc/cont-init.d/add
+COPY disable_auth_rserver.conf /etc/rstudio/disable_auth_rserver.conf
+COPY pam-helper.sh /usr/lib/rstudio-server/bin/pam-helper
+
+
+####tidyverse block 
 RUN apt-get update -qq && apt-get -y --no-install-recommends install \
   libxml2-dev \
   libcairo2-dev \
@@ -11,20 +238,9 @@ RUN apt-get update -qq && apt-get -y --no-install-recommends install \
   libssh2-1-dev \
   unixodbc-dev \
   libsasl2-dev \
-  && install2.r --error \
-    --deps TRUE \
-    tidyverse \
-    dplyr \
-    devtools \
-    formatR \
-    remotes \
-    selectr \
-    caTools \
-    BiocManager 
-	#BiocVersion
+  && Rscript -e "install.packages(c('tidyverse', 'dplyr','devtools', 'formatR', 'remotes','selectr','caTools','caTools') )"
 
-
-## bioc
+#### bioconductor block 
 RUN rm -f /var/lib/dpkg/available && rm -rf  /var/cache/apt/*
 
 # issues with '/var/lib/dpkg/available' not found
@@ -122,35 +338,84 @@ RUN apt-get update \
 	biber \
 	&& apt-get clean \
 	&& rm -rf /var/lib/apt/lists/*
-	
 
-
-## conda 
+##conda block 
 RUN apt-get -qq -y install bzip2 \
+    && mkdir  /conda \
     && curl -sSL https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -o /tmp/miniconda.sh \
-    && bash /tmp/miniconda.sh -bfp / \
+    && bash /tmp/miniconda.sh -bfp /opt/conda \
+    && ls /opt/ \
     && rm -rf /tmp/miniconda.sh \
-    && conda install -y python=3 \
-    && conda update conda \
+    && /opt/conda/bin/conda install -y python=3 \
+    && /opt/conda/bin/conda update conda \
     && apt-get -qq -y remove curl bzip2 \
     && apt-get -qq -y autoremove \
     && apt-get autoclean \
     && rm -rf /var/lib/apt/lists/* /var/log/dpkg.log \
-    && conda clean --all --yes
+    && /opt/conda/bin/conda clean --all --yes
 
 ENV PATH /opt/conda/bin:$PATH
+COPY base.yml /tmp/
+RUN conda init 
+RUN conda env update -n base --file /tmp/base.yml 
 
-COPY base.yml /root/
-COPY Rprofile-tmp $HOME/
-COPY Renviron-tmp $HOME/
 COPY Rprofile-tmp /usr/local/lib/R/etc/Rprofile.site
 COPY Renviron-tmp /usr/local/lib/R/etc/Renviron
-RUN conda init 
-RUN conda env update -n base --file /root/base.yml 
-#RUN cat /root/Rprofile-tmp > /usr/local/lib/R/etc/Rprofile.site
-#RUN cat /root/Renviron-tmp > /usr/local/lib/R/etc/Renviron
+COPY Rprofile-tmp /usr/local/lib/
+COPY Renviron-tmp /usr/local/lib/
+
+EXPOSE 8787
+
+## automatically link a shared volume for kitematic users
+VOLUME /home/rstudio/kitematic
+CMD ["/init"]
+
+RUN apt-get update \
+  && apt-get install -y --no-install-recommends \
+  gdal-bin \
+  libgdal-dev
+
+RUN apt-get clean && \
+  apt-get update &&  \
+  apt-get install -y --no-install-recommends \
+  texlive-full
+#install apache arrow (the additions to sources.list.d are required for nvidia tk which is required for plasma)
+
+RUN rm -vfr /var/lib/apt/lists/*
+
+RUN apt-get update --fix-missing && apt-get install -y -V \
+  apt-transport-https curl gnupg lsb-release
+
+RUN printf "deb http://deb.debian.org/debian $(lsb_release --codename --short)-backports main" > /etc/apt/sources.list.d/backports.list
+
+RUN curl --output /usr/share/keyrings/apache-arrow-keyring.gpg https://dl.bintray.com/apache/arrow/$(lsb_release --id --short | tr 'A-Z' 'a-z')/apache-arrow-keyring.gpg
+
+RUN printf "deb [arch=amd64 signed-by=/usr/share/keyrings/apache-arrow-keyring.gpg] https://dl.bintray.com/apache/arrow/$(lsb_release --id --short | tr 'A-Z' 'a-z')/ $(lsb_release --codename --short) main \ndeb-src [signed-by=/usr/share/keyrings/apache-arrow-keyring.gpg] https://dl.bintray.com/apache/arrow/$(lsb_release --id --short | tr 'A-Z' 'a-z')/ $(lsb_release --codename --short) main" > /etc/apt/sources.list.d/apache-arrow.list
+
+RUN curl https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
+
+RUN printf "deb http://apt.llvm.org/$(lsb_release --codename --short)/ llvm-toolchain-$(lsb_release --codename --short)-7 main\ndeb-src http://apt.llvm.org/$(lsb_release --codename --short)/ llvm-toolchain-$(lsb_release --codename --short)-7 main" > /etc/apt/sources.list.d/llvm.list
+
+RUN apt-get update && apt-get install -y -V \
+  software-properties-common && \
+  apt-add-repository contrib && \
+  apt-add-repository non-free && \
+  apt-get update && \
+  apt-get install --no-install-recommends -y -V \
+  libarrow-dev \
+  libarrow-glib-dev \
+  libplasma-dev \
+  libplasma-glib-dev \
+  libgandiva-dev \
+  libgandiva-glib-dev \
+  libparquet-dev \
+  libparquet-glib-dev
+
+# RUN Rscript -e 'library(Rcpp);sessionInfo();source("https://raw.githubusercontent.com/apache/arrow/master/r/R/install-arrow.R"); install_arrow(nightly=T, repos="https://cloud.r-project.org/")'
+#RUN Rscript -e "installed.packages()"
+
+RUN Rscript -e 'remotes::install_github("RcppCore/Rcpp", dependencies = T, repos="https://cloud.r-project.org/") ;source("https://raw.githubusercontent.com/apache/arrow/master/r/R/install-arrow.R"); install_arrow(nightly=T, repos="https://cloud.r-project.org/") ; library(Rcpp);sessionInfo();'
 
 
-
-
-
+RUN apt-get update && apt-get install -y -V libboost-all-dev 
+RUN Rscript -e "install.packages(c('flextable', 'webshot'), repos='https://cloud.r-project.org/'); webshot::install_phantomjs(); "
